spring:
  application:
    name: tlias-web-management #项目名字，可加可不加

  #配置数据库的连接信息
  datasource:
    #type用默认的 Hikari（追光者） [默认的连接池]
   url: jdbc:mysql://mysql:3306/tlias #tlias是数据库名字
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: 123

  #Mybatis的相关配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出
    map-underscore-to-camel-case: true
server:
  port: 8080


#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: cze-bucket
    region: cn-beijing
